### ISSUE TITLE
Build failed with fresh Ubuntu 20.04.3

### ISSUE THREAD

**Issue by flymike** [SLAzurin/armbian-aml-s8xx-kernel-build-steps#4]
If using a fresh installed Ubuntu 20.04 to build, beside the usual `build-essential`, packages `flex`, `bison`, `libssl-dev`, `u-boot-tools` are also needed. Without `u-boot-tools` package there is no error during the build but no `uImage` in the boot folder.

The package `unzip` also needs to be installed in order to unzip the source but you got notification for that.

Also, I have to put the path of arm gcc in CROSS_COMPILTER like is
 `CROSS_COMPILTER=~/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-`
otherwise the compiler cannot be found.

The kernel was built successfully and run correctly.

## Update
Successfully built kernel 5.15-20211031 with `wireguard` enabled in the kernel config and works great.
```
sed -i -e 's@# CONFIG_WIREGUARD is not set@CONFIG_WIREGUARD=y@g' .config
```

**Comment by SLAzurin** [comment]
Hello, and thank you for opening this issue.

Sorry for not coming back to this earlier.

As this guide is more geared towards the more advanced users, I omitted the obvious steps (such as the required `unzip` pkg).

I know the steps for this guide is not immediately obvious as I didn't polish it very well. This guide also changed over time, with some knowledge gained over time, thus making some steps harder to follow.

I did mention a step to add `PATH=$PATH:"~/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf/bin"` to the `~/.bashrc` and to `source` it in the pre-requisites section. This step would have fixed your issue with the CROSS_COMPILER path.

However, you do bring a good point about the u-boot-tools. I will specify the need for those packages if building from a separate machine in the near future. You will be added to a new `Collaborators` category once I get those changes done.

Thanks for the comments and I'm glad everything went well for you.
